api:
    endpoint: "https://www.timeapi.io/api/time/current/zone?timeZone=Europe%2F"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test